In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("/content/drive/MyDrive/ML Lab Datasets/ShopSellData.csv")
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [8]:
x=df.loc[:,:'Salary'].values
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [10]:
df.iloc[:,:-1]


Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [11]:
y=df.iloc[:,3].values
df.iloc[:,3]

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [12]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [13]:
df.tail()

Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le_x=LabelEncoder()

In [16]:
x[:,0]=le_x.fit_transform(x[:,0])

In [17]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, nan],
       [0, 35.0, 58000.0],
       [2, nan, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [37]:
ohe=OneHotEncoder()
ohe.fit_transform(df.Country.values.reshape(-1,1)).toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [38]:
label_encode_y=LabelEncoder()
y=label_encode_y.fit_transform(y)

In [23]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [26]:
x_train

array([[1, 40.0, nan],
       [0, 37.0, 67000.0],
       [2, 27.0, 48000.0],
       [2, nan, 52000.0],
       [0, 48.0, 79000.0],
       [2, 38.0, 61000.0],
       [0, 44.0, 72000.0],
       [0, 35.0, 58000.0]], dtype=object)

In [27]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [28]:
x_test

array([[1, 30.0, 54000.0],
       [1, 50.0, 83000.0]], dtype=object)

In [29]:
y_test

array([0, 0])

In [30]:
from sklearn.preprocessing import StandardScaler


In [31]:
sc_x=StandardScaler()

In [32]:
x_train_scale=sc_x.fit_transform(x_train)

In [33]:
x_test_scale=sc_x.fit_transform(x_test)

In [35]:
x_train_scale

array([[ 0.13483997,  0.25315802,         nan],
       [-0.94387981, -0.23014365,  0.44897083],
       [ 1.21355975, -1.84114924, -1.41706417],
       [ 1.21355975,         nan, -1.0242147 ],
       [-0.94387981,  1.54196248,  1.62751925],
       [ 1.21355975, -0.0690431 , -0.14030338],
       [-0.94387981,  0.89756025,  0.94003267],
       [-0.94387981, -0.55234477, -0.43494049]])

In [36]:
x_test_scale

array([[ 0., -1., -1.],
       [ 0.,  1.,  1.]])